name: Test Install and Uninstall

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test_install_uninstall:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test install.sh
      run: |
        echo -e "\033[1;34m========== Creating fake aircraft.json ==========\033[0m"
        mkdir -p /tmp/readsb
        touch /tmp/readsb/aircraft.json
        chmod a+rx /tmp/readsb
        chmod a+r /tmp/readsb/aircraft.json
        echo -e "\033[1;34m========== Creating fake systemctl ==========\033[0m"
        echo '#!/bin/bash' > /tmp/fake_systemctl
        echo "echo -e '\033[1;35m'systemctl called: \$@'\033[0m'" >> /tmp/fake_systemctl
        chmod a+x /tmp/fake_systemctl
        echo -e "\033[1;34m========== Creating debian container ==========\033[0m"
        docker run --rm -d --name=tar1090_testing -v "/tmp/fake_systemctl:/usr/bin/systemctl" -v "$(pwd)":"/workdir" -v "/tmp/readsb:/run/readsb" --workdir=/workdir debian:stable-slim sleep 86400
        echo -e "\033[1;34m========== Testing install.sh ==========\033[0m"
        docker exec -i tar1090_testing ./install.sh
        echo -e "\033[1;34m========== Testing uninstall.sh ==========\033[0m"
        docker exec -i tar1090_testing ./uinstall.sh
        echo -e "\033[1;34m========== Cleaning up ==========\033[0m"
        docker kill tar1090_testing
